name: Instalar RKE
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: descargar RKE bins
        run: wget https://github.com/rancher/rke/releases/download/v1.4.10/rke_linux-amd64
      - name: preparar RKE bins
        run: |
          mv rke_linux-amd64 rke
          chmod +x rke
          sudo mv rke /usr/local/bin/
          rke --version
